// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXaMJgXde-04OHg2cRJ1BloG_l7caiuN8',
    appId: '1:786650273847:web:334088d4698069b0f947b2',
    messagingSenderId: '786650273847',
    projectId: 'learning-management-syst-a19ce',
    authDomain: 'learning-management-syst-a19ce.firebaseapp.com',
    storageBucket: 'learning-management-syst-a19ce.firebasestorage.app',
    measurementId: 'G-VVDM82ZK3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-CxjGmfbUMleRa69uOwpWQ0mh2ipQ20Q',
    appId: '1:786650273847:android:cb1bb8fa0794adf5f947b2',
    messagingSenderId: '786650273847',
    projectId: 'learning-management-syst-a19ce',
    storageBucket: 'learning-management-syst-a19ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA47Ry9HVb6iwDYTLQ5g2QMBgWoErFl7d8',
    appId: '1:786650273847:ios:cb27224ba9bf5f6ff947b2',
    messagingSenderId: '786650273847',
    projectId: 'learning-management-syst-a19ce',
    storageBucket: 'learning-management-syst-a19ce.firebasestorage.app',
    iosBundleId: 'com.example.learningManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA47Ry9HVb6iwDYTLQ5g2QMBgWoErFl7d8',
    appId: '1:786650273847:ios:cb27224ba9bf5f6ff947b2',
    messagingSenderId: '786650273847',
    projectId: 'learning-management-syst-a19ce',
    storageBucket: 'learning-management-syst-a19ce.firebasestorage.app',
    iosBundleId: 'com.example.learningManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXaMJgXde-04OHg2cRJ1BloG_l7caiuN8',
    appId: '1:786650273847:web:457786fd5d54f8a8f947b2',
    messagingSenderId: '786650273847',
    projectId: 'learning-management-syst-a19ce',
    authDomain: 'learning-management-syst-a19ce.firebaseapp.com',
    storageBucket: 'learning-management-syst-a19ce.firebasestorage.app',
    measurementId: 'G-D8Z99KDQ45',
  );
}
